version = 0.1

[default.deploy.parameters]
stack_name = "inkfig-user-system"
resolve_s3 = true
s3_prefix = "inkfig-user-system"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"production\" CorsOrigins=\"[\\\"http://localhost:5173\\\"]\" SupabaseUrl=\"https://tudsdsnedhmufvbjbsiw.supabase.co/\" ProjectName=\"inkfig\""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
