from typing import Protocol
from uuid import UUID
from src.entities.dto.administration import UserAdministrationResponse
from src.entities.enums.role import Role


class AdministrationRepository(Protocol):
    async def list_users(self, limit: int, offset: int) -> list[UserAdministrationResponse]: ...
    async def get_user(self, user_id: UUID) -> UserAdministrationResponse | None: ...
    async def set_role(self, user_id: UUID, role: Role, actor_id: UUID) -> None: ...
    async def set_active(self, user_id: UUID, is_active: bool) -> None: ...
