from typing import Protocol
from uuid import UUID


class ProfileAvatarRepository(Protocol):
    async def replace_avatar(self, user_id: UUID, object_path: str) -> str | None: ...
    async def clear_avatar(self, user_id: UUID) -> str | None: ...


class ProfileAvatarStorage(Protocol):
    async def create_signed_upload(self, path: str) -> tuple[str, str]: ...
    async def object_is_valid(
        self, path: str, allowed_types: set[str], max_bytes: int
    ) -> bool: ...
    async def delete(self, path: str) -> None: ...
    def public_url(self, path: str) -> str: ...
