from typing import Protocol
from uuid import UUID

from src.entities.dto.settings import ProfileSettingsResponse, UpdateProfileSettingsRequest


class SettingsRepository(Protocol):
    async def get_profile(self, user_id: UUID) -> ProfileSettingsResponse | None: ...
    async def get_password_hash(self, user_id: UUID) -> str | None: ...
    async def update_profile(self, user_id: UUID, request: UpdateProfileSettingsRequest) -> ProfileSettingsResponse: ...
    async def update_password(self, user_id: UUID, password_hash: str) -> None: ...
    async def set_active(self, user_id: UUID, is_active: bool) -> None: ...
